import MobileModule from "./module/MobileModule.js";
import AosModule from "./module/AosModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
import PopupModule from "./module/PopupModule.js";
import SelectCusModule from "./module/SelectCusModule.js";
import CheckModule from "./module/CheckModule.js";
import SearchModule from "./module/SearchModule.js";
import Select2Module from "./module/Select2Module.js";
import LetterModule from "./module/LetterModule.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
import HeaderModule from "./module/HeaderModule.js";
import SideModule from "./module/SideModule.js";
import ShowHideModule from "./module/ShowHideModule.js";
import MenuModule from "./module/MenuModule.js";
import ScrollToSectionModule from "./module/ScrollToSectionModule.js";
import InputFile from "./module/InputFile.js";
import ChangeTypeInputModule from "./module/ChangeTypeInputModule.js";
import TimerModule from "./module/timeCount.js";
import LoadMoreModule from "./module/LoadMoreModule.js";
import plyrModule from "./module/plyrModule.js";
import ParallaxModule from "./module/ParallaxModule.js";
import CircleText from "./module/Circletext.js";
import textCount from "./module/textCount.js";
import sliderCus from "./module/sliderCus.js";
import SwipeFun from "./module/swipe.js";
import ProductModule from "./module/ProductModule.js";
import AnimationModule from "./module/AnimationModule.min.js";
import SwiperModule from "./module/SwiperModule.js";
import Hover from "./module/Hover.js";
import LinksMain from "./module/linksMain.js";
import inputForm from "./module/input.js";
import Splitting from "./module/splitting.js";
import SplittingJS from "./module/splitting.js";
import GSAP from "./module/gsap.js";
import GSAPJS from "./module/gsap.js";
import seeMore from "./module/seeMore.js";
import slideCustom from "./module/slideCustom.js";
import lineWave from "./module/canvasLineWave.js";
import playVideo from "./module/playVideo.js";
import uploadCV from "./module/uploadCV.js";
import SelectCheckbox from "./module/selectCheckBox.js";


window.addEventListener("DOMContentLoaded", () => {
  HeaderModule();
  Hover();
  MenuModule();
  MobileModule();
  BtnToTopModule();
  LoadMoreModule();
  SelectCusModule();
  CheckModule();
  SearchModule();
  Select2Module();
  LetterModule();
  GalleryModule();
  TabModule();
  SwiperModule();
  PopupModule();
  AosModule();
  SideModule();
  ShowHideModule();
  AnimationModule();
  ScrollToSectionModule();
  InputFile();
  ChangeTypeInputModule();
  TimerModule();
  plyrModule();
  ParallaxModule();
  CircleText();
  textCount();
  sliderCus();
  SwipeFun();
  ProductModule();
  LinksMain();
  inputForm();
  SplittingJS();
  GSAPJS();
  seeMore();
  slideCustom();
  lineWave();
  playVideo();
  uploadCV();
  SelectCheckbox();
});
